repos:
    -   hooks:
            -   args:
                    - --fix
                id: ruff
            -   id: ruff-format
        repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.9.2
    -   hooks:
            -   id: black
        repo: https://github.com/psf/black
        rev: 23.1.0
